<a href="https://colab.research.google.com/github/wbwatkinson/udemy_numpy_stack/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Section 1 of:

https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/

https://deeplearningcourses.com/c/deep-learning-prerequisites-the-numpy-stack-in-python

## Arrays vs Lists

In [21]:
import numpy as np

In [22]:
L = [1,2,3]

In [23]:
A = np.array([1,2,3])

In [24]:
for e in L:
  print(e)

1
2
3


In [25]:
for e in A:
  print(e)

1
2
3


In [26]:
L.append(4)

In [27]:
L

[1, 2, 3, 4]

In [28]:
# A.append(4) # doesn't work

In [29]:
L + [5]

[1, 2, 3, 4, 5]

In [30]:
A + np.array([4])

array([5, 6, 7])

In [31]:
A + np.array([4,5,6])

array([5, 7, 9])

In [32]:
# A + np.array([4,5]) # doesn't work

In [33]:
2 * A

array([2, 4, 6])

In [34]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [35]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [36]:
L2 = []
for e in L:
  L2.append(e + 3)

In [37]:
L2

[4, 5, 6, 7]

In [38]:
L2 = [e + 3 for e in L]

In [39]:
L2

[4, 5, 6, 7]

In [40]:
L2 = []
for e in L:
  L2.append(e**2)

In [41]:
L2

[1, 4, 9, 16]

In [42]:
A**2

array([1, 4, 9])

In [43]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [44]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [45]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [46]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [47]:
a = np.array([1,2])
b = np.array([3,4])

In [48]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [49]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [50]:
a * b

array([3, 8])

In [51]:
np.sum(a * b)

11

In [52]:
(a * b).sum()

11

In [53]:
np.dot(a, b)

11

In [54]:
a.dot(b)

11

In [55]:
b.dot(a)

11

In [56]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [57]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [58]:
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [59]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [60]:
cosangle

0.9838699100999074

In [61]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [62]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 60.949655582957725


## Matrices

In [63]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [64]:
L[0]

[1, 2]

In [65]:
L[0][1]

2

In [67]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [68]:
A[0][1]

2

In [69]:
A[0,1]

2

In [70]:
A[:,0] # returns the column at index 0 (select every row of column 0)

array([1, 3])

In [71]:
A.T

array([[1, 3],
       [2, 4]])

In [72]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [73]:
np.exp(L) # pass a list into numpy operation

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [74]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [77]:
# A.dot(B.T) # doesn't work, not aligned

In [78]:
np.linalg.det(A)

-2.0000000000000004

In [79]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [80]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [81]:
np.trace(A)

5

In [82]:
np.diag(A) # get the diagonal elements of A

array([1, 4])

In [83]:
np.diag([1,4]) # create a diagonal matrix with 1 and 4 on the diagonal

array([[1, 0],
       [0, 4]])

# Solving Linear Systems

# Generating Data

# Numpy Exercise